terraform {
  required_version = ">= 1.6.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 4.2.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.0.0"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
}

# Random suffix to keep globally-unique resource names short
resource "random_id" "suffix" {
  byte_length = 3
}

locals {
  base = "isa95-demo"
  tags = {
    project   = "factory-iq-accelerator"
    component = "isa95-data-generator"
    env       = "demo"
  }
}

# ── Resource Group ────────────────────────────────────────────────────────────
# Uses an existing resource group — the same one as the main accelerator.
# No resource block: Terraform will never try to create or destroy it.

data "azurerm_resource_group" "demo" {
  name = var.resource_group
}

# ── IoT Hub (S1 — handles the ~360 K messages/day generated by the demo) ─────

resource "azurerm_iothub" "this" {
  name                = "${local.base}-iothub"
  resource_group_name = data.azurerm_resource_group.demo.name
  location            = data.azurerm_resource_group.demo.location
  tags                = local.tags

  sku {
    name     = "S1"
    capacity = 1
  }
}

# ── Storage Account (required by Azure Functions runtime) ─────────────────────

resource "azurerm_storage_account" "functions" {
  name                     = "isa95demo${random_id.suffix.hex}sa"
  resource_group_name      = data.azurerm_resource_group.demo.name
  location                 = data.azurerm_resource_group.demo.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  tags                     = local.tags
}

# ── Log Analytics Workspace ───────────────────────────────────────────────────

resource "azurerm_log_analytics_workspace" "this" {
  name                = "${local.base}-law"
  resource_group_name = data.azurerm_resource_group.demo.name
  location            = data.azurerm_resource_group.demo.location
  sku                 = "PerGB2018"
  retention_in_days   = 30
  tags                = local.tags
}

# ── Application Insights ──────────────────────────────────────────────────────

resource "azurerm_application_insights" "this" {
  name                = "${local.base}-appinsights"
  resource_group_name = data.azurerm_resource_group.demo.name
  location            = data.azurerm_resource_group.demo.location
  workspace_id        = azurerm_log_analytics_workspace.this.id
  application_type    = "web"
  tags                = local.tags
}

# ── App Service Plan (Linux Consumption) ─────────────────────────────────────

resource "azurerm_service_plan" "this" {
  name                = "${local.base}-plan"
  resource_group_name = data.azurerm_resource_group.demo.name
  location            = data.azurerm_resource_group.demo.location
  os_type             = "Linux"
  sku_name            = "Y1"
  tags                = local.tags
}

# ── Azure Function App (.NET 10 isolated worker) ──────────────────────────────

resource "azurerm_linux_function_app" "this" {
  name                       = "${local.base}-func-${random_id.suffix.hex}"
  resource_group_name        = data.azurerm_resource_group.demo.name
  location                   = data.azurerm_resource_group.demo.location
  service_plan_id            = azurerm_service_plan.this.id
  storage_account_name       = azurerm_storage_account.functions.name
  storage_account_access_key = azurerm_storage_account.functions.primary_access_key
  tags                       = local.tags

  app_settings = {
    FUNCTIONS_WORKER_RUNTIME              = "dotnet-isolated"
    APPLICATIONINSIGHTS_CONNECTION_STRING = azurerm_application_insights.this.connection_string
    DEMO_SCENARIO                         = var.demo_scenario
    WEBSITE_RUN_FROM_PACKAGE              = "1"

    # Set to empty initially; post_deploy step injects the real device connection string.
    # Ignore drift in subsequent applies — the value is managed externally by that step.
    IoTHubDeviceConnectionString = ""
  }

  site_config {
    application_stack {
      dotnet_version              = "10.0"
      use_dotnet_isolated_runtime = true
    }
  }

  lifecycle {
    # Prevent Terraform from overwriting IoTHubDeviceConnectionString after the
    # post_deploy step injects the real device connection string.
    ignore_changes = [app_settings["IoTHubDeviceConnectionString"]]
  }
}

# ── Post-deploy: IoT Hub device + connection string injection ─────────────────
# Creates the IoT Hub device (not an ARM resource — requires az CLI),
# retrieves the device-level connection string, and injects it into the
# Function App. Runs whenever the IoT Hub or Function App is replaced.

resource "terraform_data" "post_deploy" {
  depends_on       = [azurerm_linux_function_app.this, azurerm_iothub.this]
  triggers_replace = [azurerm_iothub.this.id, azurerm_linux_function_app.this.id]

  provisioner "local-exec" {
    interpreter = ["PowerShell", "-Command"]
    command     = <<-SCRIPT
      $ErrorActionPreference = 'Stop'

      Write-Host ">>> Installing azure-iot CLI extension..."
      az extension add --name azure-iot --only-show-errors 2>$null

      Write-Host ">>> Creating IoT Hub device '${var.device_id}'..."
      az iot hub device-identity create `
        --hub-name ${azurerm_iothub.this.name} `
        --device-id ${var.device_id} `
        --output none

      Write-Host ">>> Retrieving device connection string..."
      $cs = (az iot hub device-identity connection-string show `
        --hub-name ${azurerm_iothub.this.name} `
        --device-id ${var.device_id} `
        --query connectionString `
        --output tsv)

      Write-Host ">>> Injecting connection string into Function App..."
      az functionapp config appsettings set `
        --name ${azurerm_linux_function_app.this.name} `
        --resource-group ${data.azurerm_resource_group.demo.name} `
        --settings "IoTHubDeviceConnectionString=$cs" `
        --output none

      Write-Host ">>> Post-deploy complete."
    SCRIPT
  }
}
